version: '3'

networks:
  eduvpn_network:
    ipam:
        driver: default
        config:
          - subnet: 172.20.0.0/24

services:
  eduvpnserver:
    build:
      context: "."
      dockerfile: 'ci/docker/eduvpn-server.docker'
    tty: true
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      eduvpn_network:
        ipv4_address: 172.20.0.5
    cap_add: # needed for wireguard
      - NET_ADMIN
    healthcheck:
        test: ["CMD", "systemctl", "status", "wg-quick@wg0"] # Wait for wireguard to come online
        interval: 5s
        timeout: 10s
        retries: 10
  gotest:
    build:
      context: "."
      dockerfile: 'ci/docker/go-test.docker'
    depends_on:
      eduvpnserver:
        condition: service_healthy
