name: "[Ubuntu] Test & check build"

on: [ push, pull_request ]

jobs:
  lint-go:
    name: Lint go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.15
      - uses: actions/checkout@v3
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0

  test-go:
    name: Test Go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Test with docker-compose
        run: OAUTH_EXPIRED_TTL="5" PORTAL_USER="ci" PORTAL_PASS="ci" ./ci/startcompose.sh

  build-lib:
    name: Build shared Go library
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.15
      - run: make
      - uses: actions/upload-artifact@v2
        with:
          name: shared-lib
          path: exports/lib/
          retention-days: 1
