name: Test

on: [ push, pull_request ]

jobs:
  test-go:
    name: Test Go
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - run: make test-go

  test-wrappers:
    name: Test wrappers
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11
      - uses: fwal/setup-swift@v1
        with:
          swift-version: 5
      - run: make test-wrappers
